apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-6ahz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hjab-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-6ahz@sha256:4039c790dff42d3c3b089be092b36a040f52ee1f8de9fb324b0f8c912010b549
        name: my-java-springboot
        resources: {}
status: {}
